version: "3.8"

networks:
  traefik:
    name: traefik

services:
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - DOCKER_HOST=$DOCKER_HOST
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
      # - /var/run/docker.sock:/var/run/docker.sock
      - /home/florent/docker/portainer/data:/data

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: always
    ports:
      - 9005:8080
    environment:
      - DOCKER_HOST=$DOCKEr_HOST
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
    # - /var/run/docker.sock:/var/run/docker.sock

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: unless-stopped
    ports:
      - 9010:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@local.dev
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - /home/florent/docker/pgadmin4/backup:/backup
