config:
  backup: true
  create: true
  dotpath: dotfiles
  banner: false
  chmod_on_import: false
actions:
  font-cache-refresh: fc-cache -f -v
  base: sh $HOME/.dotfiles/actions/X11/setup.sh $HOME/.dotfiles/actions/zsh.sh $HOME/.dotfiles/actions/pipewire/setup.sh $HOME/.dotfiles/actions/volta.sh $HOME/.dotfiles/actions/gpg.sh
  laptop: sh $HOME/.dotfiles/actions/libinput-gestures.sh
  work: sh $HOME/.dotfiles/actions/vanta.sh $HOME/.dotfiles/actions/work.sh $HOME/.dotfiles/actions/docker-compose.sh
dotfiles:
  d_bin:
    src: local/bin
    dst: ~/.local/bin
    chmod: 711
  f_smoke-test.sh:
    src: local/share/fonts/smoke-test.sh
    dst: ~/.local/share/fonts/smoke-test.sh
  f_fonts.conf:
    src: config/fontconfig/fonts.conf
    dst: ~/.config/fontconfig/fonts.conf
  d_zsh:
    src: config/zsh
    dst: ~/.config/zsh
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_btop:
    src: config/btop
    dst: ~/.config/btop
  d_neofetch:
    src: config/neofetch
    dst: ~/.config/neofetch
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
  f_pulsemixer.cfg:
    src: config/pulsemixer.cfg
    dst: ~/.config/pulsemixer.cfg
  d_awesome:
    src: config/awesome
    dst: ~/.config/awesome
  d_picom:
    src: config/picom
    dst: ~/.config/picom
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_X11:
    src: config/X11
    dst: ~/.config/X11
  d_gtk-3.0:
    src: config/gtk-3.0
    dst: ~/.config/gtk-3.0
  d_git:
    src: config/git
    dst: ~/.config/git
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_docker-compose.yml:
    src: docker-compose.yml
    dst: ~/docker-compose.yml
  f_microsoft-edge-stable-flags.conf:
    src: config/microsoft-edge-stable-flags.conf
    dst: ~/.config/microsoft-edge-stable-flags.conf
  f_mimeapps.list:
    src: config/mimeapps.list
    dst: ~/.config/mimeapps.list
  d_applications:
    src: local/share/applications
    dst: ~/.local/share/applications
  d_hypr:
    src: config/hypr
    dst: ~/.config/hypr
  d_qtile:
    src: config/qtile
    dst: ~/.config/qtile
  f_libinput-gestures.conf:
    src: config/libinput-gestures.conf
    dst: ~/.config/libinput-gestures.conf
  d_font_luciole:
    src: local/share/fonts/Luciole
    dst: ~/.local/share/fonts/Luciole
    actions:
      - font-cache-refresh
  d_font_cartograph:
    src: local/share/fonts/Cartograph-CF
    dst: ~/.local/share/fonts/Cartograph-CF
    actions:
      - font-cache-refresh
profiles:
  base:
    dotfiles:
      - d_bin
      - f_smoke-test.sh
      - f_fonts.conf
      - d_zsh
      - f_starship.toml
      - d_kitty
      - d_font_luciole
      - d_font_cartograph
      - d_ranger
      - f_pulsemixer.cfg
      - d_btop
      - d_neofetch
      - d_git
      - d_nvim
  desktop:
    dotfiles:
      - f_microsoft-edge-stable-flags.conf
      - f_mimeapps.list
      - d_applications
  X11:
    dotfiles:
      - d_X11
      - d_gtk-3.0
      - d_awesome
      - d_picom
      - d_rofi
  work:
    dotfiles:
      - f_docker-compose.yml
  laptop:
    dotfiles:
      - f_libinput-gestures.conf
  # hyprland:
  #   dotfiles:
  #     - d_hypr
  # qtile:
  #   dotfiles:
  #     - d_qtile
