config:
  backup: true
  create: true
  dotpath: dotfiles
  banner: false
  chmod_on_import: true
actions:
  font-cache-refresh: fc-cache -f -v
  libinput-gestures: sh ./actions/libinput-gestures.sh
  pipewire: sh ./actions/pipewire.sh
  xorg-conf: sh ./actions/xorg-conf.sh
  zsh: sh ./actions/zsh.sh
dotfiles:
  d_bin:
    src: local/bin
    dst: ~/.local/bin
    chmod: 711
  f_fonts-list.md:
    src: local/share/fonts/fonts-list.md
    dst: ~/.local/share/fonts/fonts-list.md
  f_smoke-test.sh:
    src: local/share/fonts/smoke-test.sh
    dst: ~/.local/share/fonts/smoke-test.sh
  f_fonts.conf:
    src: config/fontconfig/fonts.conf
    dst: ~/.config/fontconfig/fonts.conf
  d_zsh:
    src: config/zsh
    dst: ~/.config/zsh
    actions:
      - zsh
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_btop:
    src: config/btop
    dst: ~/.config/btop
  d_neofetch:
    src: config/neofetch
    dst: ~/.config/neofetch
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
  f_pulsemixer.cfg:
    src: config/pulsemixer.cfg
    dst: ~/.config/pulsemixer.cfg
    actions:
      - pipewire
  d_awesome:
    src: config/awesome
    dst: ~/.config/awesome
  d_picom:
    src: config/picom
    dst: ~/.config/picom
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_x11:
    src: config/X11
    dst: ~/.config/X11
    actions:
      - xorg-conf
  d_gtk-3.0:
    src: config/gtk-3.0
    dst: ~/.config/gtk-3.0
  d_git:
    src: config/git
    dst: ~/.config/git
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_docker-compose.yml:
    src: docker-compose.yml
    dst: ~/docker-compose.yml
  f_microsoft-edge-stable-flags.conf:
    src: config/microsoft-edge-stable-flags.conf
    dst: ~/.config/microsoft-edge-stable-flags.conf
  f_mimeapps.list:
    src: config/mimeapps.list
    dst: ~/.config/mimeapps.list
  d_applications:
    src: local/share/applications
    dst: ~/.local/share/applications
  d_hypr:
    src: config/hypr
    dst: ~/.config/hypr
  d_qtile:
    src: config/qtile
    dst: ~/.config/qtile
  f_libinput-gestures.conf:
    src: config/libinput-gestures.conf
    dst: ~/.config/libinput-gestures.conf
    actions:
      - libinput-gestures
  d_font_luciole:
    src: local/share/fonts/Luciole
    dst: ~/.local/share/fonts/Luciole
    actions:
      - font-cache-refresh
  d_font_cartograph:
    src: local/share/fonts/Cartograph-CF
    dst: ~/.local/share/fonts/Cartograph-CF
    actions:
      - font-cache-refresh
profiles:
  base:
    dotfiles:
      - d_bin
      - f_fonts-list.md
      - f_smoke-test.sh
      - f_fonts.conf
      - d_zsh
      - f_starship.toml
      - d_kitty
      - d_font_luciole
      - d_font_cartograph
      - d_ranger
      - f_pulsemixer.cfg
      - d_btop
      - d_neofetch
      - d_git
      - d_nvim
  desktop:
    dotfiles:
      - f_microsoft-edge-stable-flags.conf
      - f_mimeapps.list
      - d_applications
  X11:
    dotfiles:
      - d_awesome
      - d_picom
      - d_rofi
      - d_x11
      - d_gtk-3.0
  dev:
    dotfiles:
      - f_docker-compose.yml
  hyprland:
    dotfiles:
      - d_hypr
  qtile:
    dotfiles:
      - d_qtile
  laptop:
    dotfiles:
      - f_libinput-gestures.conf
