config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_bin:
    src: local/bin
    dst: ~/.local/bin
  f_fonts-list.md:
    src: local/share/fonts/fonts-list.md
    dst: ~/.local/share/fonts/fonts-list.md
  f_smoke-test.sh:
    src: local/share/fonts/smoke-test.sh
    dst: ~/.local/share/fonts/smoke-test.sh
    chmod: '755'
  f_fonts.conf:
    src: config/fontconfig/fonts.conf
    dst: ~/.config/fontconfig/fonts.conf
  d_zsh:
    src: config/zsh
    dst: ~/.config/zsh
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_btop:
    src: config/btop
    dst: ~/.config/btop
  d_neofetch:
    src: config/neofetch
    dst: ~/.config/neofetch
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
  f_pulsemixer.cfg:
    src: config/pulsemixer.cfg
    dst: ~/.config/pulsemixer.cfg
    chmod: '755'
profiles:
  base:
    dotfiles:
    - d_bin
    - f_fonts-list.md
    - f_smoke-test.sh
    - f_fonts.conf
    - d_zsh
    - f_starship.toml
    - d_kitty
  cli:
    dotfiles:
    - d_btop
    - d_neofetch
    - d_ranger
    - f_pulsemixer.cfg
